name: New Issue Trigger

on: 
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  set-current-quarter:
    permissions:
      repository-projects: read
      contents: read
      issues: write
    runs-on: ubuntu-latest
    env:
      # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.PAT }}
      # ISSUE_NUM: 1
      ISSUE_NUM: ${{ github.event.issue.number }}
      PROJECT_NUM: 3
      PROJECT_OWNER: "kons-9"
      REPONAME: "ci_sample"
      ITERATION_FIELD_NAME: "TwoWeeks"
      PROJECT_NAME: "sample"
    steps:
      - name: add project
        run: |
          gh issue edit ${{ env.ISSUE_NUM }} --add-project ${{ env.PROJECT_NAME }} -R "${{ env.PROJECT_OWNER }}/${{ env.REPONAME }}"
      - name: set current quarter
        run: |
          PROJECT_ID=$(gh project view ${{ env.PROJECT_NUM }} --owner ${{ env.PROJECT_OWNER }} --format json --jq '.id')
          echo $PROJECT_ID
          ITERATION_ID=$(gh api graphql --field project_id=$PROJECT_ID -f query='query($project_id: ID!){ node(id: $project_id) { ... on ProjectV2 { field(name: "${{ env.ITERATION_FIELD_NAME }}") { ... on ProjectV2IterationField { configuration { iterations { id } } } } } } }' --jq '.data.node.field.configuration.iterations[0].id')
          echo $ITERATION_ID
          ISSUE_ID=$(gh issue view ${{ env.ISSUE_NUM }} --json id --jq '.id' -R "${{ env.PROJECT_OWNER }}/${{ env.REPONAME }}") 
          echo $ISSUE_ID
          ITEM_PROJECT_ID="$( gh api graphql -f query='mutation($project:ID!,$local_id:ID!){addProjectV2ItemById(input:{projectId:$project,contentId:$local_id}){item{id}}}' -f project=$PROJECT_ID -f local_id=$ISSUE_ID --jq '.data.addProjectV2ItemById.item.id')"
          echo $ITEM_PROJECT_ID
          FIELD_ID=$(gh project field-list ${{ env.PROJECT_NUM }} --owner ${{ env.PROJECT_OWNER }} --format json --jq ".fields[] | select(.name == \"${{ env.ITERATION_FIELD_NAME }}\").id")
          echo $FIELD_ID
          gh project item-edit --id $ITEM_PROJECT_ID --iteration-id $ITERATION_ID --project-id $PROJECT_ID --field-id $FIELD_ID

